### ISSUE TITLE
A maximum of 50 processed files are shown in the GUI

### ISSUE THREAD

**Issue by tchnlgst** [PinkyJie/aws-transcribe-demo#18]
A maximum of 50 processed files are shown in the GUI. When the user uploads an additional file (past the 50), it will not show up in the list and it will not be processed. It would be nice to get this resolved and also to have some page enumeration ability to view all uploaded and processed files.

**Comment by PinkyJie** [comment]
Hey @tchnlgst , as the project name indicates, this is only for demo purpose, I'm not going to add new feature like pagination for that, if you really want that feature, you are welcome to fork the project and implement on your own.
