### ISSUE TITLE
An error occurred: S3BucketVoiceassistdevaudiofilebucket - voice-assist-dev-audio-file-bucket already exists.

### ISSUE THREAD

**Issue by dariushazimi** [PinkyJie/aws-transcribe-demo#2]
Hi Wenbo Jie,

I get:

`An error occurred: S3BucketVoiceassistdevaudiofilebucket - voice-assist-dev-audio-file-bucket already exists.
`

`CloudFormation - CREATE_FAILED - AWS::S3::Bucket - S3BucketVoiceassistdevaudiofilebucket
`

![image](https://user-images.githubusercontent.com/622048/56479544-e9f2af00-6483-11e9-9ace-57214577c6d1.png)

The error says that the bucket already exists but when I check the S3, there is no bucket with this name?

![image](https://user-images.githubusercontent.com/622048/56479949-042d8c80-6486-11e9-8417-ee50ba774c10.png)

Any idea?

Thanks

**Comment by dariushazimi** [comment]
Re-run the yarn deploy again after removing the stack and it seems to work.

**Comment by PinkyJie** [comment]
This is the same issue as #3 , as I mentioned there, S3 bucket name must be unique globally. Try the workaround mentioned in #3 to see if it works. Thanks!

**Comment by PinkyJie** [comment]
Hey @dariushazimi , as I mentioned in #3, the latest deployment flow should fix all such kind of issues. I'll close this one for now, feel free to reopen if you think it's not fixed.
