### ISSUE TITLE
Module not found: Error: Can't resolve '../stack.json'

### ISSUE THREAD

**Issue by dariushazimi** [PinkyJie/aws-transcribe-demo#3]
When I run the yarn build in the front end, I get an error saying

`Module not found: Error: Can't resolve '../stack.json' in '/Users/darius/project/aws/aws-transcribe-demo/packages/frontend/src/components'`

 - `cd packages/frontend`
  - `yarn build

![image](https://user-images.githubusercontent.com/622048/56481402-d1d35d80-648c-11e9-9dd4-faeb16cc3762.png)

Any help would be great.
Thanks.

**Comment by PinkyJie** [comment]
Hi @dariushazimi, `stack.json` is generated from the backend build script, you need to have a successful deployment for cloud formation first. If your cloudformation fails, you need to go to AWS console and manually delete the stack first before redeploy. Sometimes deleting stack won't delete all your resources(like non-empty S3), you need to do that manually.

Hope it helps.

**Comment by dariushazimi** [comment]
Hi @PinkyJie I am trying it again and have removed the stacks, all the S3 buckets but still the same. Have you run into this issue?
Thanks

**Comment by dariushazimi** [comment]
@PinkyJie 
On a new AWS env in a new VPC I made sure there are no refrences of any deployment.
But when the scripts get to creating S3, I gives an error.

Any idea?

![image](https://user-images.githubusercontent.com/622048/57028496-3de05f00-6c0d-11e9-8f8e-361ae1813531.png)

**Comment by PinkyJie** [comment]
I think I know why, S3 bucket name must be globally unique, I guess the name `S3BucketVoiceassistdevaudiofilebucket` is already used by your previous task, could you go to your S3 console to check if you already has a bucket with this name?

If not, it might be used by others, I didn't consider this scenario before, one workaround is to update file `packages/backend/serverless.yml`:
* line 12 ->   `AudioFileBucketName: voice-assist-${self:provider.stage}-audio-file-bucket-1`
* replace `S3BucketVoiceassistdevaudiofilebucket` to `S3BucketVoiceassistdevaudiofilebucket1`

This will create a S3 bucket with a new name, let me know if it works. At the same time, I need to think about how to fix this issue gracefully. Thanks!

**Comment by dariushazimi** [comment]
Thanks, @PinkyJie trying it now. Will let you know.

**Comment by dariushazimi** [comment]
That worked fine. (need to add this to the docs). 
Now when I try to upload an MP3 file (size < 7 mb) I get upload failed.:

![image](https://user-images.githubusercontent.com/622048/57094040-7bacb880-6cdd-11e9-8334-2bf3ff63e370.png)

Any idea?

**Comment by Neuronys** [comment]
@PinkyJie Hello, I've managed to create the backend with the advice you gave in this thread, but I can't build the frontend as I miss the stack.json file, apparently not generated by the backend.
any help from you will be highly appreciated, even the stack.json template to use.
Thanks
<img width="1196" alt="Capture d’écran 2019-05-25 à 13 09 22" src="https://user-images.githubusercontent.com/33979693/58368527-a4942800-7eee-11e9-987d-1fe0389a877a.png">

**Comment by lostsheep007** [comment]
Hello @PinkyJie I am also stuck at the stack.json error when trying to build the frontend. The backend cloudformation completed successfully. Tried to use the template json that was generated renamed as stack.json but still no luck getting this working when frontend copied to s3.

**Comment by PinkyJie** [comment]
Hi guys @dariushazimi @Neuronys @lostsheep007 , sorry for the late response, was busy for last few months. I did a major update for this repo to replace serverless with AWS CDK, this will resolve the "stack.json" issue. 

Here is a demo site: https://d3hk9i6re8qnvi.cloudfront.net/

Could you try again (either with the above dome site or with your own deployment)? Let me know if you have other issues.
