### ISSUE TITLE
Error Running Yarn Deploy

### ISSUE THREAD

**Issue by mjpete3** [PinkyJie/aws-transcribe-demo#8]
The deploy package is using Nodejs8.10 which no longer works with the AWS CLI.

Error Message:

21/52 | 12:53:45 PM | CREATE_FAILED        | AWS::Lambda::Function                           | BucketNotificationsHandler050a0587b7544547bf325f094a3db834 (BucketNotificationsHandler050a0587b7544547bf325f094a3db8347ECC3691) The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: e04c47d3-d70a-49eb-8f35-d2e313c5af22)

**Comment by PinkyJie** [comment]
Hi @mjpete3, thanks for reporting the issue, I'll have a look.

**Comment by PinkyJie** [comment]
@mjpete3 I upgraded all the dependencies and now the issue should be fixed.

**Comment by mjpete3** [comment]
Excellent.   Thank you. 

⁣Get BlueMail for Android ​
